### PR TITLE
Update Gradle wrapper

### PR DESCRIPTION
**Pull request by johnjohndoe**

### CODE REVIEW

**Comment by msteiger** [comment]
The latest version is 4.0.1 now .. maybe worth upgrading before merging?

**Comment by johnjohndoe** [comment]
I can take a look at this week.

**Comment by johnjohndoe** [comment]
Updated.

**Comment by johnjohndoe** [comment]
Oh nice (above): how can I integrate VersionEye in the pull request workflow?

**Comment by reiz** [comment]
@johnjohndoe If the gradle file is monitored by VersionEye through the GitHub integration then every commit in a pull request should be checked by VersionEye automatically. See here: https://blog.versioneye.com/2016/08/16/pull-request-support-for-github/.

**Pull request merged**
